document.writeln('');
document.writeln('<!DOCTYPE html>');
document.writeln('<html lang="en" >');
document.writeln('');
document.writeln('<head>');
document.writeln('  <meta charset="UTF-8">');
document.writeln('  ');
document.writeln('  ');
document.writeln('    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500&display=swap" rel="stylesheet">');
document.writeln('  ');
document.writeln('  ');
document.writeln('  ');
document.writeln('<style>');
document.writeln(':root {');
document.writeln('  --bg-color: rgb(20, 20, 20);');
document.writeln('  --card-color: rgb(23, 23, 23);');
document.writeln('}');
document.writeln('');
document.writeln('body {');
document.writeln('  align-items: center;');
document.writeln('  background-color: var(--bg-color);');
document.writeln('  display: flex;');
document.writeln('  height: 100vh;');
document.writeln('  justify-content: center;');
document.writeln('  margin: 0px;');
document.writeln('  overflow: hidden;');
document.writeln('  padding: 0px;');
document.writeln('}');
document.writeln('');
document.writeln('#cards {');
document.writeln('  display: flex;');
document.writeln('  flex-wrap: wrap;');
document.writeln('  gap: 8px;  ');
document.writeln('  max-width: 916px;');
document.writeln('  width: calc(100% - 20px);');
document.writeln('}');
document.writeln('');
document.writeln('#cards:hover > .card::after {');
document.writeln('  opacity: 1;');
document.writeln('}');
document.writeln('');
document.writeln('.card {');
document.writeln('  background-color: rgba(255, 255, 255, 0.1);');
document.writeln('  border-radius: 10px;');
document.writeln('  cursor: pointer;');
document.writeln('  display: flex;');
document.writeln('  height: 260px;');
document.writeln('  flex-direction: column;');
document.writeln('  position: relative;');
document.writeln('  width: 300px;  ');
document.writeln('}');
document.writeln('');
document.writeln('.card:hover::before {');
document.writeln('  opacity: 1;');
document.writeln('}');
document.writeln('');
document.writeln('.card::before,');
document.writeln('.card::after {');
document.writeln('  border-radius: inherit;');
document.writeln('  content: "";');
document.writeln('  height: 100%;');
document.writeln('  left: 0px;');
document.writeln('  opacity: 0;');
document.writeln('  position: absolute;');
document.writeln('  top: 0px;');
document.writeln('  transition: opacity 500ms;');
document.writeln('  width: 100%;');
document.writeln('}');
document.writeln('');
document.writeln('.card::before {');
document.writeln('  background: radial-gradient(');
document.writeln('    800px circle at var(--mouse-x) var(--mouse-y), ');
document.writeln('    rgba(255, 255, 255, 0.06),');
document.writeln('    transparent 40%');
document.writeln('  );');
document.writeln('  z-index: 3;');
document.writeln('}');
document.writeln('');
document.writeln('.card::after {  ');
document.writeln('  background: radial-gradient(');
document.writeln('    600px circle at var(--mouse-x) var(--mouse-y), ');
document.writeln('    rgba(255, 255, 255, 0.4),');
document.writeln('    transparent 40%');
document.writeln('  );');
document.writeln('  z-index: 1;');
document.writeln('}');
document.writeln('');
document.writeln('.card > .card-content {');
document.writeln('  background-color: var(--card-color);');
document.writeln('  border-radius: inherit;');
document.writeln('  display: flex;');
document.writeln('  flex-direction: column;');
document.writeln('  flex-grow: 1;');
document.writeln('  inset: 1px;');
document.writeln('  padding: 10px;');
document.writeln('  position: absolute;');
document.writeln('  z-index: 2;');
document.writeln('}');
document.writeln('');
document.writeln('/* -- ↓ ↓ ↓ extra card content styles ↓ ↓ ↓ -- */');
document.writeln('');
document.writeln('h1, h2, h3, h4, span {');
document.writeln('  color: rgb(240, 240, 240);');
document.writeln('  font-family: "Rubik", sans-serif;');
document.writeln('  font-weight: 400;');
document.writeln('  margin: 0px;');
document.writeln('}');
document.writeln('');
document.writeln('i {  ');
document.writeln('  color: rgb(240, 240, 240);');
document.writeln('}');
document.writeln('');
document.writeln('.card-image {');
document.writeln('  align-items: center;');
document.writeln('  display: flex;');
document.writeln('  height: 140px;');
document.writeln('  justify-content: center;');
document.writeln('  overflow: hidden;');
document.writeln('}');
document.writeln('');
document.writeln('.card-image > i {');
document.writeln('  font-size: 6em;');
document.writeln('  opacity: 0.25;');
document.writeln('}');
document.writeln('');
document.writeln('.card-info-wrapper {');
document.writeln('  align-items: center;');
document.writeln('  display: flex;');
document.writeln('  flex-grow: 1;');
document.writeln('  justify-content: flex-start;');
document.writeln('  padding: 0px 20px;');
document.writeln('}');
document.writeln('');
document.writeln('.card-info {');
document.writeln('  align-items: flex-start;');
document.writeln('  display: flex;');
document.writeln('  gap: 10px;');
document.writeln('}');
document.writeln('');
document.writeln('.card-info > i {  ');
document.writeln('  font-size: 1em;');
document.writeln('  height: 20px;');
document.writeln('  line-height: 20px;');
document.writeln('}');
document.writeln('');
document.writeln('.card-info-title > h3 {');
document.writeln('  font-size: 1.1em;');
document.writeln('  line-height: 20px;');
document.writeln('}');
document.writeln('');
document.writeln('.card-info-title > h4 {');
document.writeln('  color: rgba(255, 255, 255, 0.5);');
document.writeln('  font-size: 0.85em;');
document.writeln('  margin-top: 8px;');
document.writeln('}');
document.writeln('');
document.writeln('/* -- ↓ ↓ ↓ some responsiveness ↓ ↓ ↓ -- */');
document.writeln('');
document.writeln('@media(max-width: 1000px) {');
document.writeln('  body {');
document.writeln('    align-items: flex-start;  ');
document.writeln('    overflow: auto;');
document.writeln('  }');
document.writeln('  ');
document.writeln('  #cards {    ');
document.writeln('    max-width: 1000px;');
document.writeln('    padding: 10px 0px;');
document.writeln('  }');
document.writeln('  ');
document.writeln('  .card {');
document.writeln('    flex-shrink: 1;');
document.writeln('    width: calc(50% - 4px);');
document.writeln('  }');
document.writeln('}');
document.writeln('');
document.writeln('@media(max-width: 500px) {');
document.writeln('  .card {');
document.writeln('    height: 180px;');
document.writeln('  }');
document.writeln('  ');
document.writeln('  .card-image {');
document.writeln('    height: 80px;  ');
document.writeln('  }');
document.writeln('  ');
document.writeln('  .card-image > i {');
document.writeln('    font-size: 3em;');
document.writeln('  }');
document.writeln('    ');
document.writeln('  .card-info-wrapper {');
document.writeln('    padding: 0px 10px;');
document.writeln('  }');
document.writeln('  ');
document.writeln('  .card-info > i { ');
document.writeln('    font-size: 0.8em; ');
document.writeln('  }');
document.writeln('  ');
document.writeln('  .card-info-title > h3 {');
document.writeln('    font-size: 0.9em;');
document.writeln('  }');
document.writeln('');
document.writeln('  .card-info-title > h4 {');
document.writeln('    font-size: 0.8em;');
document.writeln('    margin-top: 4px;');
document.writeln('  }');
document.writeln('}');
document.writeln('');
document.writeln('@media(max-width: 320px) {');
document.writeln('  .card {');
document.writeln('    width: 100%;');
document.writeln('  }');
document.writeln('}');
document.writeln('');
document.writeln('/* -- ↓ ↓ ↓ YouTube link styles ↓ ↓ ↓ -- */');
document.writeln('');
document.writeln('#youtube-link {');
document.writeln('  bottom: 10px;');
document.writeln('}');
document.writeln('');
document.writeln('#youtube-link > i {');
document.writeln('  color: rgb(239, 83, 80);');
document.writeln('}');
document.writeln('');
document.writeln('#source-link {');
document.writeln('  bottom: 60px;');
document.writeln('}');
document.writeln('');
document.writeln('#source-link > i {');
document.writeln('  color: rgb(94, 106, 210);');
document.writeln('}');
document.writeln('');
document.writeln('.link {');
document.writeln('  align-items: center;');
document.writeln('  backdrop-filter: blur(3px);');
document.writeln('  background-color: rgba(255, 255, 255, 0.05);');
document.writeln('  border: 1px solid rgba(255, 255, 255, 0.1);');
document.writeln('  border-radius: 6px;');
document.writeln('  box-shadow: 2px 2px 2px rgba(0, 0, 0, 0.1);');
document.writeln('  cursor: pointer;  ');
document.writeln('  display: inline-flex;');
document.writeln('  gap: 5px;');
document.writeln('  left: 10px;');
document.writeln('  padding: 10px 20px;');
document.writeln('  position: fixed;');
document.writeln('  text-decoration: none;');
document.writeln('  z-index: 100;');
document.writeln('}');
document.writeln('');
document.writeln('.link:hover {');
document.writeln('  background-color: rgba(255, 255, 255, 0.1);');
document.writeln('  border: 1px solid rgba(255, 255, 255, 0.2);');
document.writeln('}');
document.writeln('');
document.writeln('.link > i, .link > span {');
document.writeln('  height: 20px;');
document.writeln('  line-height: 20px;');
document.writeln('}');
document.writeln('');
document.writeln('.link > span {');
document.writeln('  color: white;');
document.writeln('}');
document.writeln('</style>');
document.writeln('');
document.writeln('  ');
document.writeln('  ');
document.writeln('  ');
document.writeln('</head>');
document.writeln('');
document.writeln('<body>');
document.writeln('  <div id="cards">');
document.writeln('  <div class="card">');
document.writeln('    <div class="card-content">');
document.writeln('      <div class="card-image">');
document.writeln('        <i class="fa-duotone fa-apartment"></i>');
document.writeln('      </div>');
document.writeln('      <div class="card-info-wrapper">');
document.writeln('        <div class="card-info">');
document.writeln('          <i class="fa-duotone fa-apartment"></i>');
document.writeln('          <div class="card-info-title">');
document.writeln('            <h3>Apartments</h3>  ');
document.writeln('            <h4>Places to be apart. Wait, what?</h4>');
document.writeln('          </div>    ');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <div class="card">');
document.writeln('    <div class="card-content">');
document.writeln('      <div class="card-image">');
document.writeln('        <i class="fa-duotone fa-unicorn"></i>');
document.writeln('      </div>');
document.writeln('      <div class="card-info-wrapper">');
document.writeln('        <div class="card-info">');
document.writeln('          <i class="fa-duotone fa-unicorn"></i>');
document.writeln('          <div class="card-info-title">');
document.writeln('            <h3>Unicorns</h3>  ');
document.writeln('            <h4>A single corn. Er, I mean horn.</h4>');
document.writeln('          </div>    ');
document.writeln('        </div>  ');
document.writeln('      </div>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <div class="card">');
document.writeln('    <div class="card-content">');
document.writeln('      <div class="card-image">');
document.writeln('        <i class="fa-duotone fa-blender-phone"></i>');
document.writeln('      </div>');
document.writeln('      <div class="card-info-wrapper">');
document.writeln('        <div class="card-info">');
document.writeln('          <i class="fa-duotone fa-blender-phone"></i>');
document.writeln('          <div class="card-info-title">');
document.writeln('            <h3>Blender Phones</h3>  ');
document.writeln('            <h4>These absolutely deserve to exist.</h4>');
document.writeln('          </div>    ');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <div class="card">');
document.writeln('    <div class="card-content">');
document.writeln('      <div class="card-image">');
document.writeln('        <i class="fa-duotone fa-person-to-portal"></i>');
document.writeln('      </div>');
document.writeln('      <div class="card-info-wrapper">');
document.writeln('        <div class="card-info">');
document.writeln('          <i class="fa-duotone fa-person-to-portal"></i>');
document.writeln('          <div class="card-info-title">');
document.writeln('            <h3>Adios</h3>  ');
document.writeln('            <h4>See you...</h4>');
document.writeln('          </div>    ');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <div class="card">');
document.writeln('    <div class="card-content">');
document.writeln('      <div class="card-image">');
document.writeln('        <i class="fa-duotone fa-person-from-portal"></i>');
document.writeln('      </div>');
document.writeln('      <div class="card-info-wrapper">');
document.writeln('        <div class="card-info">');
document.writeln('          <i class="fa-duotone fa-person-from-portal"></i>');
document.writeln('          <div class="card-info-title">');
document.writeln('            <h3>I mean hello</h3>  ');
document.writeln('            <h4>...over here.</h4>');
document.writeln('          </div>    ');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('  <div class="card">');
document.writeln('    <div class="card-content">');
document.writeln('      <div class="card-image">');
document.writeln('        <i class="fa-duotone fa-otter"></i>');
document.writeln('      </div>');
document.writeln('      <div class="card-info-wrapper">');
document.writeln('        <div class="card-info">');
document.writeln('          <i class="fa-duotone fa-otter"></i>');
document.writeln('          <div class="card-info-title">');
document.writeln('            <h3>Otters</h3>  ');
document.writeln('            <h4>Look at me, imma cute lil fella.</h4>');
document.writeln('          </div>    ');
document.writeln('        </div>');
document.writeln('      </div>');
document.writeln('    </div>');
document.writeln('  </div>');
document.writeln('</div>');
document.writeln('');
document.writeln('<a id="source-link" class="link" href="https://linear.app/features" target="_blank">');
document.writeln('  <i class="fa-solid fa-link"></i>');
document.writeln('  <span class="roboto-mono">Source</span>');
document.writeln('</a>');
document.writeln('');
document.writeln('<a id="youtube-link" class="link" href="https://youtu.be/htGfnF1zN4g" target="_blank">');
document.writeln('  <i class="fa-brands fa-youtube"></i>');
document.writeln('  <span>5 min Tutorial</span>');
document.writeln('</a>');
document.writeln('  ');
document.writeln('  <scr'+'ipt src=\'https://codepen.io/Hyperplexed/pen/xxYJYjM/54407644e24173ad6019b766443bf2a6.js\'></scr'+'ipt>');
document.writeln('      <scr'+'ipt id="rendered-js" >');
document.writeln('doc'+'ument.getElementById("cards").onmousemove = e => {');
document.writeln('  for(const card of doc'+'ument.getElementsByClassName("card")) {');
document.writeln('    const rect = card.getBoundingClientRect(),');
document.writeln('          x = e.clientX - rect.left,');
document.writeln('          y = e.clientY - rect.top;');
document.writeln('');
document.writeln('    card.style.setProperty("--mouse-x", `${x}px`);');
document.writeln('    card.style.setProperty("--mouse-y", `${y}px`);');
document.writeln('  };');
document.writeln('}');
document.writeln('    </scr'+'ipt>');
document.writeln('');
document.writeln('  ');
document.writeln('</body>');
document.writeln('');
document.writeln('</html>');
